version: '3'
services:
  postgresdb:
    image: 'postgres:13'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=josh
      - POSTGRES_DB=personal-projects
    volumes:
      - ./sql/.db-data/postgres/:/var/lib/postgresql/data/
